// Copyright 2014 <chaishushan{AT}gmail.com>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Auto Generated By 'go generate', DONOT EDIT!!!

package image

import (
	"image"
	"image/color"
	"reflect"
	"unsafe"

	colorExt "github.com/chai2010/image/color"
)

type Gray struct {
	M struct {
		Pix    []uint8 // []struct{ Y uint8 }
		Stride int
		Rect   image.Rectangle
	}
}

// NewGray returns a new Gray with the given bounds.
func NewGray(r image.Rectangle) *Gray {
	return new(Gray).Init(make([]uint8, 1*r.Dx()*r.Dy()), 1*r.Dx(), r)
}

func (p *Gray) Init(pix []uint8, stride int, rect image.Rectangle) *Gray {
	*p = Gray{
		M: struct {
			Pix    []uint8
			Stride int
			Rect   image.Rectangle
		}{
			Pix:    pix,
			Stride: stride,
			Rect:   rect,
		},
	}
	return p
}

func (p *Gray) BaseType() image.Image { return asBaseType(p) }
func (p *Gray) Pix() []byte           { return p.M.Pix }
func (p *Gray) Stride() int           { return p.M.Stride }
func (p *Gray) Rect() image.Rectangle { return p.M.Rect }
func (p *Gray) Channels() int         { return 1 }
func (p *Gray) Depth() reflect.Kind   { return reflect.Uint8 }

func (p *Gray) ColorModel() color.Model { return colorExt.GrayModel }

func (p *Gray) Bounds() image.Rectangle { return p.M.Rect }

func (p *Gray) At(x, y int) color.Color {
	return p.GrayAt(x, y)
}

func (p *Gray) GrayAt(x, y int) colorExt.Gray {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return colorExt.Gray{}
	}
	i := p.PixOffset(x, y)
	return *(*colorExt.Gray)(unsafe.Pointer(&p.M.Pix[i]))
}

// PixOffset returns the index of the first element of Pix that corresponds to
// the pixel at (x, y).
func (p *Gray) PixOffset(x, y int) int {
	return (y-p.M.Rect.Min.Y)*p.M.Stride + (x-p.M.Rect.Min.X)*1
}

func (p *Gray) Set(x, y int, c color.Color) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	c1 := p.ColorModel().Convert(c).(colorExt.Gray)
	*(*colorExt.Gray)(unsafe.Pointer(&p.M.Pix[i])) = c1
	return
}

func (p *Gray) SetGray(x, y int, c colorExt.Gray) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	*(*colorExt.Gray)(unsafe.Pointer(&p.M.Pix[i])) = c
	return
}

// SubImage returns an image representing the portion of the image p visible
// through r. The returned value shares pixels with the original image.
func (p *Gray) SubImage(r image.Rectangle) image.Image {
	r = r.Intersect(p.M.Rect)
	// If r1 and r2 are Rectangles, r1.Intersect(r2) is not guaranteed to be inside
	// either r1 or r2 if the intersection is empty. Without explicitly checking for
	// this, the Pix[i:] expression below can panic.
	if r.Empty() {
		return &Gray{}
	}
	i := p.PixOffset(r.Min.X, r.Min.Y)
	return new(Gray).Init(
		p.M.Pix[i:],
		p.M.Stride,
		r,
	)
}

// Opaque scans the entire image and reports whether it is fully opaque.
func (p *Gray) Opaque() bool {
	return true
}

func (p *Gray) Draw(r image.Rectangle, src Image, sp image.Point) Image {
	panic("TODO")
}
